<?php
declare(strict_types=1);

namespace Gravityrd\GravityClient;


/**
 * Contains a list of recommended items. This class is here only to describe the result,
 * the actual result will not be an instance of this class because of json deserialization.
 */
class GravityItemRecommendation
{
    public function __construct()
    {
    }

    /**
     *
     * Array containing the recommended items.
     * This is populated only if the scenario specifies to do so, otherwise this is null.
     * itemIds is always populated.
     * The items in this list only have the NameValues specified by the scenario.
     * The list of NameValues specified by the scenario can be overridden by the
     * GravityRecommendationContext resultNameValues on a per request basis.
     *
     * @var GravityItem[]
     */
    public $items;

    /**
     *
     * The identifiers of the recommended items. Only if not a NameValue recommendation.
     *
     * @var int
     */
    public $itemIds;

    /**
     *
     * The unique identifier of the recommendation generated by the recommendation engine.
     * Strings in the PHP client are always UTF-8 encoded.
     *
     * @var string
     */
    public $recommendationId;

    /**
     * Array containing additional name-value pairs for recommendations.
     * e.g.: AllItemCount for paging responses.
     *
     * @var GravityNameValue[]
     */
    public $outputNameValues;
}